### ISSUE TITLE
Add Typescript types

### ISSUE THREAD

**Issue by RodolfoSilva** [jrgarciadev/react-iconly#4]
I think we can add Typescript types or move the project to use Typescript.

If you're interested in it, I can do it today @jrgarciadev. I'm using this lib on a project I'm working on.

**Comment by jrgarciadev** [comment]
Hey @RodolfoSilva thanks for your contribution, I'm going to review your changes.

**Comment by jrgarciadev** [comment]
Hey @RodolfoSilva, I was reviewing your PR, but there is a problem, the file "react-iconly.d.ts" should be in the "dist" folder so that later it can be distributed in the npm package, so you must add the command to compile typescript next to the command to do the build something like this `"build": "microbundle && tsc"` and "tsconfig.json" file,  could you guide yourself with this [post](https://medium.com/javascript-in-plain-english/how-to-type-check-your-javascript-without-typescript-563e5d384576)  

Thanks!
